-- CREATE DATABASE mobile_money;
CREATE TABLE OPERATEUR (ID INTEGER PRIMARY KEY AUTOINCREMENT, NOM VARCHAR(50) NOT NULL);

CREATE TABLE PREFIXE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CODE VARCHAR(6) NOT NULL UNIQUE,
    OPERATEUR_ID INTEGER,
    FOREIGN KEY (OPERATEUR_ID) REFERENCES OPERATEUR (ID)
);

CREATE TABLE ADMINISTRATEUR (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM VARCHAR(50) NOT NULL,
    PRENOM VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    MDP VARCHAR(255) NOT NULL
);

CREATE TABLE ADMINISTRATION (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ADMINISTRATEUR_ID INTEGER,
    OPERATEUR_ID INTEGER,
    FOREIGN KEY (ADMINISTRATEUR_ID) REFERENCES ADMINISTRATEUR (ID),
    FOREIGN KEY (OPERATEUR_ID) REFERENCES OPERATEUR (ID)
);

CREATE TABLE OPERATION (ID INTEGER PRIMARY KEY AUTOINCREMENT, LIBELLE VARCHAR(50) NOT NULL);

CREATE TABLE CLIENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM VARCHAR(50) NOT NULL,
    PRENOM VARCHAR(50) NOT NULL,
    OPERATEUR_ID INTEGER,
    TELEPHONE VARCHAR(15) NOT NULL UNIQUE,
    SOLDE DECIMAL(20, 2) NOT NULL DEFAULT 0.00,
    MDP VARCHAR(255) NOT NULL,
    FOREIGN KEY (OPERATEUR_ID) REFERENCES OPERATEUR (ID)
);

CREATE TABLE FRAIS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MONTANT_INF DECIMAL(20, 2) NOT NULL,
    MONTANT_SUP DECIMAL(20, 2) NOT NULL,
    MONTANT_FRAIS DECIMAL(20, 2) NOT NULL,
    OPERATION_ID INTEGER,
    FOREIGN KEY (OPERATION_ID) REFERENCES OPERATION (ID)
);

CREATE TABLE TRANSACTIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MONTANT DECIMAL(20, 2) NOT NULL,
    FRAIS DECIMAL(20, 2) NOT NULL,
    DATE DATETIME NOT NULL,
    OPERATION_ID INTEGER,
    CLIENT_HOTE INTEGER,
    CLIENT_CIBLE INTEGER,
    VALEUR_COMMISION DECIMAL(20, 2) NOT NULL DEFAULT 0.00,
    FOREIGN KEY (CLIENT_HOTE) REFERENCES CLIENT (ID),
    FOREIGN KEY (CLIENT_CIBLE) REFERENCES CLIENT (ID),
    FOREIGN KEY (OPERATION_ID) REFERENCES OPERATION (ID)
);

CREATE TABLE COMISSION (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOM VARCHAR(50) NOT NULL, -- Ex: 'Telma -> Orange'
    OPERATEUR_SOURCE_ID INTEGER NOT NULL,
    OPERATEUR_CIBLE_ID INTEGER NOT NULL,
    TAUX_POURCENTAGE DECIMAL(5, 2) NOT NULL, -- Ex: 10.00 (pour 10%)
    FOREIGN KEY (OPERATEUR_SOURCE_ID) REFERENCES OPERATEUR (ID),
    FOREIGN KEY (OPERATEUR_CIBLE_ID) REFERENCES OPERATEUR (ID)
);

CREATE TABLE PROMOTION_FRAIS (ID INTEGER PRIMARY KEY AUTOINCREMENT, VALEUR DECIMAL(5, 2) NOT NULL);

ALTER TABLE client ADD COLUMN epargne DECIMAL(20, 2); 